export const generateSampleData = () => {
  const menuItems = [
    {
      id: "101",
      name: "Espresso",
      description: "Rich and bold single shot",
      price: 3.5,
      categoryId: "1",
      available: true,
      popular: true,
      stockQuantity: 100,
      lowStockThreshold: 20,
    },
    {
      id: "102",
      name: "Cappuccino",
      description: "Espresso with steamed milk foam",
      price: 4.5,
      categoryId: "1",
      available: true,
      popular: true,
      stockQuantity: 95,
      lowStockThreshold: 20,
    },
    {
      id: "103",
      name: "Latte",
      description: "Smooth espresso with steamed milk",
      price: 4.75,
      categoryId: "1",
      available: true,
      popular: true,
      stockQuantity: 90,
      lowStockThreshold: 20,
    },
    {
      id: "104",
      name: "Americano",
      description: "Espresso with hot water",
      price: 3.75,
      categoryId: "1",
      available: true,
      popular: false,
      stockQuantity: 88,
      lowStockThreshold: 20,
    },
    {
      id: "105",
      name: "Mocha",
      description: "Chocolate espresso with steamed milk",
      price: 5.25,
      categoryId: "1",
      available: true,
      popular: true,
      stockQuantity: 75,
      lowStockThreshold: 20,
    },
    {
      id: "106",
      name: "Flat White",
      description: "Microfoam milk with ristretto shots",
      price: 4.5,
      categoryId: "1",
      available: true,
      popular: false,
      stockQuantity: 82,
      lowStockThreshold: 20,
    },
    // Tea
    {
      id: "201",
      name: "English Breakfast",
      description: "Classic black tea blend",
      price: 3.25,
      categoryId: "2",
      available: true,
      popular: true,
      stockQuantity: 60,
      lowStockThreshold: 15,
    },
    {
      id: "202",
      name: "Green Tea",
      description: "Light and refreshing",
      price: 3.25,
      categoryId: "2",
      available: true,
      popular: false,
      stockQuantity: 55,
      lowStockThreshold: 15,
    },
    {
      id: "203",
      name: "Chamomile",
      description: "Soothing herbal tea",
      price: 3.5,
      categoryId: "2",
      available: true,
      popular: false,
      stockQuantity: 40,
      lowStockThreshold: 15,
    },
    {
      id: "204",
      name: "Earl Grey",
      description: "Bergamot-infused black tea",
      price: 3.5,
      categoryId: "2",
      available: true,
      popular: true,
      stockQuantity: 48,
      lowStockThreshold: 15,
    },
    {
      id: "205",
      name: "Mint Tea",
      description: "Fresh peppermint leaves",
      price: 3.25,
      categoryId: "2",
      available: true,
      popular: false,
      stockQuantity: 52,
      lowStockThreshold: 15,
    },
    // Pastries
    {
      id: "301",
      name: "Croissant",
      description: "Buttery and flaky",
      price: 3.75,
      categoryId: "3",
      available: true,
      popular: true,
      stockQuantity: 25,
      lowStockThreshold: 10,
    },
    {
      id: "302",
      name: "Chocolate Muffin",
      description: "Rich chocolate chip muffin",
      price: 4.25,
      categoryId: "3",
      available: true,
      popular: true,
      stockQuantity: 18,
      lowStockThreshold: 10,
    },
    {
      id: "303",
      name: "Blueberry Scone",
      description: "Fresh blueberries in every bite",
      price: 4.0,
      categoryId: "3",
      available: true,
      popular: false,
      stockQuantity: 15,
      lowStockThreshold: 10,
    },
    {
      id: "304",
      name: "Cinnamon Roll",
      description: "Sweet cinnamon swirl with icing",
      price: 4.5,
      categoryId: "3",
      available: true,
      popular: true,
      stockQuantity: 12,
      lowStockThreshold: 8,
    },
    {
      id: "305",
      name: "Almond Cookie",
      description: "Crunchy almond biscuit",
      price: 2.75,
      categoryId: "3",
      available: true,
      popular: false,
      stockQuantity: 30,
      lowStockThreshold: 10,
    },
    // Sandwiches
    {
      id: "401",
      name: "Turkey Club",
      description: "Turkey, bacon, lettuce, tomato",
      price: 8.5,
      categoryId: "4",
      available: true,
      popular: true,
      stockQuantity: 20,
      lowStockThreshold: 8,
    },
    {
      id: "402",
      name: "Veggie Wrap",
      description: "Fresh vegetables with hummus",
      price: 7.5,
      categoryId: "4",
      available: true,
      popular: false,
      stockQuantity: 18,
      lowStockThreshold: 8,
    },
    {
      id: "403",
      name: "Chicken Panini",
      description: "Grilled chicken with pesto",
      price: 9.0,
      categoryId: "4",
      available: true,
      popular: true,
      stockQuantity: 15,
      lowStockThreshold: 8,
    },
    {
      id: "404",
      name: "BLT",
      description: "Bacon, lettuce, tomato classic",
      price: 7.75,
      categoryId: "4",
      available: true,
      popular: false,
      stockQuantity: 22,
      lowStockThreshold: 8,
    },
    // Cold Drinks
    {
      id: "501",
      name: "Iced Coffee",
      description: "Cold brew over ice",
      price: 4.25,
      categoryId: "5",
      available: true,
      popular: true,
      stockQuantity: 45,
      lowStockThreshold: 15,
    },
    {
      id: "502",
      name: "Iced Latte",
      description: "Espresso with cold milk",
      price: 4.75,
      categoryId: "5",
      available: true,
      popular: true,
      stockQuantity: 42,
      lowStockThreshold: 15,
    },
    {
      id: "503",
      name: "Lemonade",
      description: "Fresh squeezed lemonade",
      price: 3.75,
      categoryId: "5",
      available: true,
      popular: false,
      stockQuantity: 35,
      lowStockThreshold: 12,
    },
    {
      id: "504",
      name: "Orange Juice",
      description: "Freshly squeezed",
      price: 4.5,
      categoryId: "5",
      available: true,
      popular: false,
      stockQuantity: 28,
      lowStockThreshold: 12,
    },
    {
      id: "505",
      name: "Smoothie Bowl",
      description: "Berry smoothie with granola",
      price: 7.5,
      categoryId: "5",
      available: true,
      popular: true,
      stockQuantity: 16,
      lowStockThreshold: 8,
    },
    // Snacks
    {
      id: "601",
      name: "Chips",
      description: "Assorted flavors",
      price: 2.25,
      categoryId: "6",
      available: true,
      popular: false,
      stockQuantity: 50,
      lowStockThreshold: 15,
    },
    {
      id: "602",
      name: "Granola Bar",
      description: "Oats and honey",
      price: 2.5,
      categoryId: "6",
      available: true,
      popular: false,
      stockQuantity: 45,
      lowStockThreshold: 15,
    },
    {
      id: "603",
      name: "Fruit Cup",
      description: "Fresh seasonal fruits",
      price: 4.5,
      categoryId: "6",
      available: true,
      popular: true,
      stockQuantity: 20,
      lowStockThreshold: 10,
    },
    {
      id: "604",
      name: "Yogurt Parfait",
      description: "Greek yogurt with berries",
      price: 5.25,
      categoryId: "6",
      available: true,
      popular: true,
      stockQuantity: 18,
      lowStockThreshold: 8,
    },
  ];

  const categories = [
    { id: "1", name: "Coffee", color: "hsl(24, 95%, 53%)", order: 1 },
    { id: "2", name: "Tea", color: "hsl(142, 76%, 36%)", order: 2 },
    { id: "3", name: "Pastries", color: "hsl(38, 92%, 50%)", order: 3 },
    { id: "4", name: "Sandwiches", color: "hsl(340, 82%, 52%)", order: 4 },
    { id: "5", name: "Cold Drinks", color: "hsl(217, 91%, 60%)", order: 5 },
    { id: "6", name: "Snacks", color: "hsl(280, 67%, 55%)", order: 6 },
  ];

  return { menuItems, categories };
};
