import { RouterProvider, createRouter } from '@tanstack/react-router';
import React from 'react';
import { Toaster } from 'sonner';
import './index.css';

/* This will be auto-generated by TanStack Router after running dev server */
import { routeTree } from './routeTree.gen';

/* Create router instance with the route tree */
export const router = createRouter({ routeTree });

/* Register router for type safety */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const App: React.FC = () => {
  return (
    <>
      <RouterProvider router={router} />
      <Toaster
        richColors
        position="top-center"
        closeButton
        toastOptions={{
          style: {
            fontSize: '1.15rem',
            fontWeight: '600',
            padding: '1rem 1.5rem',
            borderRadius: '1rem',
            minWidth: '300px',
          },
          duration: 3000,
        }}
      />
    </>
  );
};

export default App;
