# Generated by Django 5.2.7 on 2025-12-03 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_category_menuitem_slug_alter_menuitem_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MenuItem",
            new_name="Item",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"], "verbose_name_plural": "items"},
        ),
    ]
