# Generated by Django 5.2.7 on 2025-12-03 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_rename_menuitem_item_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="stock",
        ),
    ]
