# Generated by Django 5.2.7 on 2025-12-19 02:34

import apps.menu.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=apps.menu.models.menu_image_upload_path,
            ),
        ),
    ]
